{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otomi-keycloak-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otomi-keycloak-operator.fullname" . }}-edit-keycloak
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "post"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otomi-keycloak-operator.fullname" . }}-edit-keycloak
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "otomi-keycloak-operator.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "otomi-keycloak-operator.fullname" . }}-edit-keycloak
  apiGroup: rbac.authorization.k8s.io
{{- end }}