apiVersion: v2
name: otomi
description: A Helm chart for installing otomi in Kubernetes
home: https://otomi.io/
icon: https://otomi.io/img/otomi-logo.svg
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - otomi
  - otomi.io
  - container-management
  - cicd
  - multi-tenancy
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - observability
  - metrics
  - tracing
sources:
  - https://github.com/redkubes/otomi-core
