apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-operator
  namespace: knative-operator
  labels:
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/version: "1.15.5"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: knative-operator
        app.kubernetes.io/name: knative-operator
        app.kubernetes.io/version: "1.15.5"
    spec:
      serviceAccountName: knative-operator
      containers:
        - name: knative-operator
          image: gcr.io/knative-releases/knative.dev/operator/cmd/operator@sha256:29855c3d4d4afdd91c42061b24be26b4a0543f4af54c4be903cc812244a6672c
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: knative.dev/operator
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: KUBERNETES_MIN_VERSION
              value: ""
          ports:
            - name: metrics
              containerPort: 9090
---