apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-operator
  namespace: knative-operator
  labels:
    app.kubernetes.io/version: "1.15.5"
    app.kubernetes.io/name: knative-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-webhook
  namespace: knative-operator
  labels:
    app.kubernetes.io/version: "1.15.5"
    app.kubernetes.io/name: knative-operator

---