bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: argocd-operator-artifacts
    installed: {{ $a | get "argocd.enabled" }}
    namespace: argocd
    labels:
      pkg: argocd
      stage: init
    <<: *raw
  - name: istio-operator
    installed: true
    namespace: istio-operator
    labels:
      pkg: istio
      stage: init
    <<: *default
  - name: keycloak-artifacts
    installed: true
    namespace: keycloak
    labels:
      pkg: keycloak
      stage: init
    <<: *raw
  - name: keycloak-operator
    installed: true
    namespace: keycloak
    labels:
      pkg: keycloak-operator
      stage: init
    <<: *default
  - name: vault-operator-artifacts
    installed: {{ $a | get "vault.enabled" }}
    namespace: vault
    labels:
      pkg: vault
      group: secrets
    <<: *raw
