bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: harbor
    installed: {{ $a | get "harbor.enabled" }}
    namespace: harbor
    labels:
      pkg: harbor
    <<: *default
  - name: oauth2-proxy
    # TODO: remove oauth dependency
    installed: true
    namespace: istio-system
    labels:
      tag: ingress
      pkg: oauth2-proxy
    <<: *default
  - name: oauth2-proxy-artifacts
    # TODO: remove oauth dependency
    installed: true
    namespace: istio-system
    labels:
      tag: ingress
      pkg: oauth2-proxy
    <<: *raw
  - name: otomi-api
    installed: true
    namespace: otomi
    labels:
      pkg: otomi
    <<: *default
  - name: otomi-console
    installed: true
    namespace: otomi
    labels:
      pkg: otomi
    <<: *default
