bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: keycloak-operator-cr
    installed: true
    namespace: keycloak
    labels:
      pkg: keycloak
      stage: init
    <<: *rawCR
  - name: argocd-operator-cr
    installed: {{ $a | get "argocd.enabled" }}
    namespace: argocd
    labels:
      pkg: argocd
      stage: init
    <<: *rawCR
  - name: istio-operator-artifacts
    installed: true
    namespace: istio-operator
    labels:
      pkg: istio
      stage: init
    chart: ../charts/raw
    values:
      - ../values/istio-operator/istio-operator-raw.gotmpl
      - snippets/common.gotmpl
  - name: external-secrets-artifacts
    installed: {{ $a | get "external-secrets.enabled" }}
    disableValidationOnInstall: true
    namespace: external-secrets
    labels:
      pkg: external-secrets
      group: secrets
    <<: *raw

