{{- $v := .Values }}
{{- range $p := $v.policies }}
{{- if and (eq $p.name "restrict-volume-types") ($p.enabled) }}
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restrict-volume-types
  annotations:
    policies.kyverno.io/title: Restrict Volume Types
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: {{ .severity }}
    policies.kyverno.io/subject: Pod,Volume
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/description: >-
      In addition to restricting HostPath volumes, the restricted pod security profile
      limits usage of non-core volume types to those defined through PersistentVolumes.
      This policy blocks any other type of volume other than those in the allow list.
  labels: {{- include "team-ns.chart-labels" $ | nindent 4 }}
spec:
  validationFailureAction: {{ .action }}
  background: true
  failurePolicy: Fail
  rules:
    - name: restricted-volumes
      match:
        any:
        - resources:
            kinds:
              - Pod
      skipBackgroundRequests: true
      validate:
        message: >-
          Only the following types of volumes may be used: configMap, csi, downwardAPI,
          emptyDir, ephemeral, persistentVolumeClaim, projected, and secret.
        deny:
          conditions:
            all:
            - key: "{{`{{ request.object.spec.volumes[].keys(@)[] || '' }}`}}"
              operator: AnyNotIn
              {{- with .customValues }}
              value: {{ . | toYaml | nindent 14 }}
              {{- end }}
{{- end }}
{{- end }}
