name: Scheduled - minimal with DNS, KMS and Letsencrypt
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  start-integration-test-minimal-dns:
    name: Start integration test (minimal)
    uses: ./.github/workflows/integration.yml
    secrets: inherit
    with:
      install_profile: minimal
      domain: dns-integration.dev-akamai-apl.net
      kms: age
      certificate: letsencrypt_production
      generate_password: 'yes'
