{{- $v := .Values }}
{{- if get (index $v.apps "external-secrets") "enabled" }}
{{- $ns := $.Release.Namespace }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-{{ $ns }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $ns }}
      auth:
        serviceAccount:
            name: eso-k8s-store
{{- end }}